# -*- coding: utf-8 -*-
"""PlaylistCreator_colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lJCo_cn3Ph2uv00J3lNOlSwm1Sr2uSrV
"""

# Commented out IPython magic to ensure Python compatibility.
import shutil
!pip install pygit2==1.12.2
# %cd /content
folder_path = "/content/InformaticaUmanistica"
shutil.rmtree(folder_path, ignore_errors=True)
!git clone https://github.com/MaxPignatti/InformaticaUmanistica.git
# %cd /content/InformaticaUmanistica/frontend
!npm i
!npm run build

from google.colab import output
output.serve_kernel_port_as_window(8084)

from flask import Flask, send_from_directory, jsonify, request
import os
app = Flask(__name__, static_folder='/content/InformaticaUmanistica/frontend/build', static_url_path='')

# Serve the index.html file for the root URL
@app.route('/')
def serve():
    return send_from_directory(app.static_folder, 'index.html')

# Serve static files from the build directory
@app.route('/<path:path>')
def static_proxy(path):
    file_name = path.split('/')[-1]
    directory_name = os.path.join(app.static_folder, '/'.join(path.split('/')[:-1]))
    return send_from_directory(directory_name, file_name)

@app.route('/api/sendText',methods=['POST'])
def hello():
    data = request.json
    text = data.get('text')
    #Usiamo il modello
    return "YES" #Risposta dal modello (o creiamo la playlist e ritorniamo un success)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8084)